### ISSUE TITLE
Vores tests

### ISSUE THREAD

**Issue by StefanMich** [SW10IoT/report#11]
Tonsvis af cases - different language constructs
Python has evolved a lot over the years, supporting OOP and Functional Programming - this means that a lot of constructs are added giving a lot of test cases.
Show examples where a test is useful to cover all corner cases.

Dynamic language - the interpreter does not give much in terms of debugging - tests provides safety

Complexity of program analysis

Write a draft x2

**Comment by StefanMich** [comment]
First draft produced,

not mentioned: Complexity of program analysis (what did we mean)

**Comment by Thalmann** [comment]
Added the if constrol structure cases that are present in the ast as abstracts graph to illustrate the many different and complex cases - see if it is useful :)

**Comment by Thalmann** [comment]
2 kommentarer fra stuffe:
- graferne er lidt store, men det er måske svært at gøre så meget ved når besrkivelserne er så lange
- der mangler måske en klar forklaring af hvad expr og stmt\* er
