### ISSUE TITLE
Security Vulnerabilities

### ISSUE THREAD

**Issue by StefanMich** [SW10IoT/report#14]
XSS, command injection, SQLi

eksempler

**Comment by Thalmann** [comment]
Correct text so it fits the refactored examples. Wait for: https://github.com/SW10IoT/experiments/issues/1

**Comment by StefanMich** [comment]
maybe move the relevant files to pyt/examples

**Comment by Thalmann** [comment]
Updated sql injection examples text, appendix and example.

Directory traversal is also top dollar.
