### ISSUE TITLE
Sikkerhedsaspekter vi undersøger

### ISSUE THREAD

**Issue by StefanMich** [SW10IoT/report#15]
Intro til hvorfor det er nødvendigt at analysere sikkerhed

OWASP
Python web frameworks (find en kilde der siger at der bliver lavet fejl?)

**Comment by Thalmann** [comment]
Draft - se lige hvad du synes @stufkan

**Comment by StefanMich** [comment]
Omskrevet så det er vores intro, 
se Intro, samt starten på det nye kapitel "Preliminaries"

**Comment by Thalmann** [comment]
Dø den her: https://github.com/SW10IoT/report/issues/16 Hvis den her kan bruges
