### ISSUE TITLE
Funny or unusual language constructs

### ISSUE THREAD

**Issue by Thalmann** [SW10IoT/report#18]
Leave a comment with proposols pls ty vm

**Comment by Thalmann** [comment]
While statement

Has an optional else clause

while True:
code block
else:
code block

**Comment by Thalmann** [comment]
Generator expressions

Concise, good readability, good writeability

example:
(x*y for x in range(10) for y in bar(x))

**Comment by Thalmann** [comment]
List comprehension

Concise, good readability, good writeability

example:
squares = [x**2 for x in range(10)]

**Comment by StefanMich** [comment]
Consider if there are more constructs!

**Comment by StefanMich** [comment]
for with while

**Comment by Thalmann** [comment]
Awesome afsnit
