### ISSUE TITLE
Limitations of PyT

### ISSUE THREAD

**Issue by Thalmann** [SW10IoT/report#20]
dynamic:
- "Having no dynamic analysis is a major disadvantage" - Rene
- Monkey patching

import own module/library module etc. Also as statement

Decorators
- "let" at implementere -> meget tæt på function call 
- context for forskellige decorators, som fortæller analysen om den kan være farlig

Inbuilt/library 
- meget kort, om hvorfor det er besværligt at inddrage alt, selvom man har koden - lang analyse 

Pas på overlap med https://github.com/SW10IoT/report/issues/39

**Comment by Thalmann** [comment]
Skal ikke fokusere på cfg constructs!

**Comment by Thalmann** [comment]
Jeg går i gang med: "Having no dynamic analysis is a major disadvantage" - Rene

**Comment by StefanMich** [comment]
9055050 + 01047f0
