### ISSUE TITLE
Future works

### ISSUE THREAD

**Issue by StefanMich** [SW10IoT/report#45]
Udvid med Django, pyt er parametriseret, så det er let at gå igang med
Limitiations

others?

**Comment by Thalmann** [comment]
Optimering af pyt  -hvordan handler vi ~500000 cfg nodes ..

**Comment by StefanMich** [comment]
bedre håndtering af sanitising. Man kunne muligvis godt garantere santisation i cases hvor der ikke er branches mellem source of sink
