### ISSUE TITLE
Project handler modulet

### ISSUE THREAD

**Issue by StefanMich** [SW10IoT/report#47]
imports
evt. decorators
håndtering af CFG'er

**Comment by Thalmann** [comment]
Husk module_definitions modulet og den stack der er i cfg.py

**Comment by Thalmann** [comment]
Should contain a description of:
\begin{itemize}
\item project_handler module
\item module_definitions module
\item module_definitions_stack in cfg module
\item General description of how the import solution is designed
\end{itemize}
