### ISSUE TITLE
Interprocedural analysis

### ISSUE THREAD

**Issue by Thalmann** [SW10IoT/report#6]
- [x] Håndtering af funktioner 
- [x] Shadow variables
- [x] Polyvariance

Evt. eksempel CFG

**Comment by StefanMich** [comment]
Tror muligvis ikke det er relevant? Har svært ved at se hvor det passer ind, måske vi skal spørge Rene om det er godt af have med?

**Comment by Thalmann** [comment]
Rene siger det er guld

**Comment by Thalmann** [comment]
Incorporate the idea of one CFG is a whole program and that functions a basically just in-lined in the source code.
