### ISSUE TITLE
Intro til python

### ISSUE THREAD

**Issue by StefanMich** [SW10IoT/report#8]
Sprog detaljer
- dynamisk
- key constructs

**Comment by Thalmann** [comment]
Spørg Rene om vi skal introducere python ligesom schwarzbach har gjort med PIP

**Comment by Thalmann** [comment]
Det skal være kortfattet intro.

Dyk ned i underlige konstruktioner og specielle ting ved python.

**Comment by Thalmann** [comment]
Brug de CFG's der er lavet og præsenter source code ved siden af.

**Comment by Thalmann** [comment]
Rene kan afgøre den sidste todo da vi er uenige :)
