### ISSUE TITLE
Intro til problemet

### ISSUE THREAD

**Issue by StefanMich** [SW10IoT/report#9]
Statisk analyse
Hvorfor er det interessant?
Hvorfor er det svært - Rice s. 3 i Schwarzbach

**Comment by Thalmann** [comment]
Moved undecidable problem to its own section - easier for ref and big enough for its own section IMO

**Comment by Thalmann** [comment]
Maybe add an example?

**Comment by Thalmann** [comment]
Can you take a look @stufkan :)
